#!/bin/bash
# // Color
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
NC='\e[0m'
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# // Getting BOT
export CHATID="6617783693"
export KEY="6751589620:AAHwjP6dzZhuqeyUOdYFc6742Q1YUVF1EjM"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "             MENU SHADOWSHOCKS            $NC"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "  ${ORANGE}1.${NC} \033[0;36m Create Account Shadowshocks WS/GRPC${NC}"
echo -e "  ${ORANGE}2.${NC} \033[0;36m Create Trial Shadowshocks WS/GRPC${NC}"
echo -e "  ${ORANGE}3.${NC} \033[0;36m Delete Account Shadowsocks WS/GRPC${NC}"
echo -e "  ${ORANGE}4.${NC} \033[0;36m Renew Shadowsocks Account${NC}"
echo -e "  ${ORANGE}5.${NC} \033[0;36m Check Shadowsocks login Account${NC}"
echo -e "  ${ORANGE}6.${NC} \033[0;36m Check Config Shadowsocks  Account${NC}"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 6 ] : " menu
case $menu in
1)
    addss
    ;;
2)
    trialss
    ;;
3)
    delss
    ;;
4)
    renewss
    ;;
5)
    cekss
    ;;
6)
    user-ss
    ;;   
 
*)
    menu
    ;;
esac
