#!/bin/bash
Green="\e[92;1m"
RED="\033[31m"
YELLOW="\033[33m"
BLUE="\033[36m"
FONT="\033[0m"
GREENBG="\033[42;37m"
REDBG="\033[41;37m"
OK="${Green}--->${FONT}"
ERROR="${RED}[ERROR]${FONT}"
GRAY="\e[1;30m"
NC='\e[0m'
red='\e[1;31m'
green='\e[0;32m'
DF='\e[39m'
Bold='\e[1m'
Blink='\e[5m'
yell='\e[33m'
red='\e[31m'
green='\e[32m'
blue='\e[34m'
PURPLE='\e[35m'
cyan='\e[36m'
Lred='\e[91m'
Lgreen='\e[92m'
Lyellow='\e[93m'
NC='\e[0m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
LIGHT='\033[0;37m'
grenbo="\e[92;1m"
red() { echo -e "\\033[32;1m${*}\\033[0m"; }
# Getting
export CHATID="6617783693"
export KEY="6751589620:AAHwjP6dzZhuqeyUOdYFc6742Q1YUVF1EjM"
export TIME="10"
export URL="https://api.telegram.org/bot$KEY/sendMessage"
clear
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "                 MENU VLESS              $NC"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e "\033[1;93m┌──────────────────────────────────────────┐\033[0m"
echo -e "  ${ORANGE}1.${NC} \033[0;36m Create Account XRAY Vless WS/GRPC${NC}"
echo -e "  ${ORANGE}2.${NC} \033[0;36m Create Trial XRAY Vless WS/GRPC${NC}"
echo -e "  ${ORANGE}3.${NC} \033[0;36m Delete Account XRAY Vless WS/GRPC${NC}"
echo -e "  ${ORANGE}4.${NC} \033[0;36m Renew Vless Account${NC}"
echo -e "  ${ORANGE}5.${NC} \033[0;36m Check Vless login Account${NC}"
echo -e "  ${ORANGE}6.${NC} \033[0;36m Check Config Vless Account${NC}"
echo -e "\033[1;93m└──────────────────────────────────────────┘\033[0m"
echo -e ""
read -p "Select From Options [ 1 - 6 ] : " menu
case $menu in
1)  clear ;
    addvless
    ;;
2) clear ;
    trialvless
    ;;
3) clear ;
    delvless
    ;;
4) clear ;
    renewvless
    ;;
5) clear ;
    cekvless
    ;;
6) clear ;
    user-vless
    ;;
*)
    menu
    ;;
esac
